proxy-sync:
  enabled: true
  host: 127.0.0.1
  port: 29175
  secret: change-me
  interval-seconds: 3

formatting:
  # Используется, если у LuckPerms-группы нет suffix.
  default-suffix: " &#F8BEFBБЕТА"

settings:
  # 10 обновлений движения в секунду достаточно визуально и существенно легче для сервера.
  movement-period-ticks: 2
  motd-count-enabled: true
  use-essentials-spawn: true
  physics:
    enabled: true
    max-step-height: 1
    max-fall-check: 64
    max-safe-drop: 3.5
    avoid-liquids: true
    avoid-hazards: true
    anti-flight: true

population:
  timezone: Europe/Moscow
  first-join-delay-seconds: 15
  minimum-bots: 3
  maximum-bots: 15
  session-minutes: { min: 60, max: 360 }
  profile-cooldown-minutes: { min: 120, max: 360 }
  afk-minutes: { min: 5, max: 60 }
  visible-percent: { min: 20, max: 60 }
  region:
    world: spawn
    center-x: 30
    center-z: 9
    radius: 30
